// Regenerates texture-average-colors.generated.ts from the block textures in public/game:
//   bun src/applications/game/lod/colors/generate-block-colors.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Texture } from "../../blocks";
import { averageVisibleColor, decodeRgbaPng } from "./png-average-color";

const REPOSITORY_ROOT = join(import.meta.dir, "../../../../..");
export const BLOCK_TEXTURE_DIRECTORY = join(REPOSITORY_ROOT, "public/game");
const GENERATED_FILE_PATH = join(import.meta.dir, "texture-average-colors.generated.ts");

export function computeTextureAverageColors(textureDirectory: string = BLOCK_TEXTURE_DIRECTORY): Record<string, number> {
  const colorsByFileName: Record<string, number> = {};
  const fileNames = [...new Set(Object.values(Texture))].sort();
  for (const fileName of fileNames) {
    const image = decodeRgbaPng(new Uint8Array(readFileSync(join(textureDirectory, fileName))));
    colorsByFileName[fileName] = averageVisibleColor(image);
  }
  return colorsByFileName;
}

export function renderGeneratedModule(colorsByFileName: Record<string, number>): string {
  const lines = Object.entries(colorsByFileName).map(([fileName, color]) => {
    const literal = color < 0 ? "-1" : `0x${color.toString(16).padStart(6, "0")}`;
    return `  "${fileName}": ${literal},`;
  });
  return [
    "// Generated by generate-block-colors.ts from public/game. Do not edit by hand.",
    "// sRGB 0xRRGGBB average of the pixels the main shader keeps (alpha >= 0.5), averaged in linear light; -1 = fully transparent.",
    "",
    "export const TEXTURE_AVERAGE_COLORS: Readonly<Record<string, number>> = {",
    ...lines,
    "};",
    "",
  ].join("\n");
}

if (import.meta.main) {
  writeFileSync(GENERATED_FILE_PATH, renderGeneratedModule(computeTextureAverageColors()));
  console.log(`Wrote ${GENERATED_FILE_PATH}`);
}
