// Generated by generate-block-faces.node.ts from fixtures/ground-reference.json.gz. Do not edit.
// Exceptions to "sturdy faces == attachable faces / collision full" for the default state of each block.

/** Faces (bit 1 << Direction ordinal) where Block.isFaceFull(support shape) || isFaceFull(collision shape) holds, when different from the sturdy faces. */
export const ATTACH_FACE_EXCEPTIONS: Readonly<Record<string, number>> = {
  "minecraft:acacia_leaves": 63,
  "minecraft:azalea_leaves": 63,
  "minecraft:birch_leaves": 63,
  "minecraft:cherry_leaves": 63,
  "minecraft:chorus_flower": 63,
  "minecraft:dark_oak_leaves": 63,
  "minecraft:flowering_azalea_leaves": 63,
  "minecraft:jungle_leaves": 63,
  "minecraft:mangrove_leaves": 63,
  "minecraft:oak_leaves": 63,
  "minecraft:spruce_leaves": 63,
};

/** BlockState.isCollisionShapeFullBlock where it differs from "all six faces sturdy". */
export const COLLISION_FULL_OVERRIDES: Readonly<Record<string, boolean>> = {
  "minecraft:acacia_leaves": true,
  "minecraft:azalea_leaves": true,
  "minecraft:birch_leaves": true,
  "minecraft:cherry_leaves": true,
  "minecraft:chorus_flower": true,
  "minecraft:dark_oak_leaves": true,
  "minecraft:flowering_azalea_leaves": true,
  "minecraft:jungle_leaves": true,
  "minecraft:mangrove_leaves": true,
  "minecraft:mud": false,
  "minecraft:oak_leaves": true,
  "minecraft:soul_sand": false,
  "minecraft:spruce_leaves": true,
};
