// Node-only generator: turns fixtures/ground-reference.json.gz (recorded from the real 1.20.6 classes by
// ../fixtures/GroundReference.java) into block-faces.generated.ts. Run:
//   bun src/applications/game/worldgen/engine/features/feature-types/ground/support/generate-block-faces.node.ts

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";

const MODULE_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = join(MODULE_DIRECTORY, "..", "fixtures", "ground-reference.json.gz");
const GENERATED_PATH = join(MODULE_DIRECTORY, "block-faces.generated.ts");

const reference = JSON.parse(gunzipSync(readFileSync(FIXTURE_PATH)).toString()) as {
  attachFaceExceptions: Record<string, number>;
  collisionFullOverrides: Record<string, boolean>;
};

function renderRecord(record: Record<string, unknown>): string {
  return Object.entries(record)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`)
    .join("\n");
}

writeFileSync(
  GENERATED_PATH,
  `// Generated by generate-block-faces.node.ts from fixtures/ground-reference.json.gz. Do not edit.
// Exceptions to "sturdy faces == attachable faces / collision full" for the default state of each block.

/** Faces (bit 1 << Direction ordinal) where Block.isFaceFull(support shape) || isFaceFull(collision shape) holds, when different from the sturdy faces. */
export const ATTACH_FACE_EXCEPTIONS: Readonly<Record<string, number>> = {
${renderRecord(reference.attachFaceExceptions)}
};

/** BlockState.isCollisionShapeFullBlock where it differs from "all six faces sturdy". */
export const COLLISION_FULL_OVERRIDES: Readonly<Record<string, boolean>> = {
${renderRecord(reference.collisionFullOverrides)}
};
`,
);
console.log(`wrote ${GENERATED_PATH}`);
