import { BlockType } from "../../../blocks";

// Exact Minecraft names (without "minecraft:") for plants, fungi, light sources and other cross-shaped blocks.
export const PLANT_BLOCKS: Record<string, BlockType> = {
  short_grass: BlockType.TALL_GRASS,
  grass: BlockType.TALL_GRASS,
  tall_grass: BlockType.TALL_GRASS,
  fern: BlockType.FERN,
  large_fern: BlockType.FERN,
  dead_bush: BlockType.DEAD_BUSH,
  sweet_berry_bush: BlockType.FERN,
  crimson_roots: BlockType.FERN,
  warped_roots: BlockType.FERN,
  nether_sprouts: BlockType.FERN,
  big_dripleaf: BlockType.FERN,
  big_dripleaf_stem: BlockType.FERN,
  small_dripleaf: BlockType.FERN,
  pitcher_plant: BlockType.AGAVE,
  dandelion: BlockType.DANDELION,
  poppy: BlockType.POPPY,
  wither_rose: BlockType.POPPY,
  allium: BlockType.ALLIUM,
  azure_bluet: BlockType.AZURE_BLUET,
  blue_orchid: BlockType.BLUE_ORCHID,
  cornflower: BlockType.CORNFLOWER,
  oxeye_daisy: BlockType.OXEYE_DAISY,
  lily_of_the_valley: BlockType.LILY_OF_THE_VALLEY,
  torchflower: BlockType.TORCHFLOWER,
  red_tulip: BlockType.TULIP_RED,
  orange_tulip: BlockType.TULIP_ORANGE,
  white_tulip: BlockType.TULIP_WHITE,
  pink_tulip: BlockType.TULIP_PINK,
  sunflower: BlockType.SUNFLOWER,
  lilac: BlockType.LILAC,
  rose_bush: BlockType.ROSE_BUSH,
  peony: BlockType.PEONY,
  pink_petals: BlockType.PINK_PETALS,
  brown_mushroom: BlockType.BROWN_MUSHROOM,
  red_mushroom: BlockType.RED_MUSHROOM,
  brown_mushroom_block: BlockType.BROWN_MUSHROOM_BLOCK,
  red_mushroom_block: BlockType.RED_MUSHROOM_BLOCK,
  mushroom_stem: BlockType.MUSHROOM_STEM,
  lily_pad: BlockType.LILY_PAD,
  sugar_cane: BlockType.REEDS,
  bamboo: BlockType.REEDS,
  bamboo_sapling: BlockType.REEDS,
  cactus: BlockType.CACTUS,
  vine: BlockType.VINE,
  cave_vines: BlockType.CAVE_VINES,
  cave_vines_plant: BlockType.CAVE_VINES,
  hanging_roots: BlockType.HANGING_ROOTS,
  cobweb: BlockType.COBWEB,
  azalea: BlockType.LEAVES_AZALEA,
  flowering_azalea: BlockType.LEAVES_AZALEA_FLOWERING,
  azalea_leaves: BlockType.LEAVES_AZALEA,
  flowering_azalea_leaves: BlockType.LEAVES_AZALEA_FLOWERING,
  mangrove_roots: BlockType.MANGROVE_ROOTS,
  mangrove_propagule: BlockType.SAPLING,
  wheat: BlockType.SAVANNA_GRASS,
  carrots: BlockType.TALL_GRASS,
  potatoes: BlockType.TALL_GRASS,
  beetroots: BlockType.TALL_GRASS,
  melon_stem: BlockType.TALL_GRASS,
  pumpkin_stem: BlockType.TALL_GRASS,
  attached_melon_stem: BlockType.TALL_GRASS,
  attached_pumpkin_stem: BlockType.TALL_GRASS,
  melon: BlockType.MELON,
  pumpkin: BlockType.PUMPKIN,
  carved_pumpkin: BlockType.PUMPKIN,
  jack_o_lantern: BlockType.PUMPKIN,
  hay_block: BlockType.HAY_BLOCK,
  torch: BlockType.TORCH,
  wall_torch: BlockType.TORCH,
  soul_torch: BlockType.TORCH,
  soul_wall_torch: BlockType.TORCH,
  redstone_torch: BlockType.TORCH,
  redstone_wall_torch: BlockType.TORCH,
  lantern: BlockType.TORCH,
  soul_lantern: BlockType.TORCH,
  campfire: BlockType.TORCH,
  soul_campfire: BlockType.TORCH,
  glowstone: BlockType.GLOWSTONE,
  shroomlight: BlockType.GLOWSTONE,
  sea_lantern: BlockType.GLOWSTONE,
  redstone_lamp: BlockType.GLOWSTONE,
  ochre_froglight: BlockType.GLOWSTONE,
  pearlescent_froglight: BlockType.GLOWSTONE,
  verdant_froglight: BlockType.GLOWSTONE,
};

// Plants that are always underwater: the block cell is water in the game.
export const ALWAYS_WATER_BLOCKS = ["seagrass", "tall_seagrass", "kelp", "kelp_plant", "bubble_column"];

// Blocks that sit in water unless the state says waterlogged=false (Minecraft defaults them to waterlogged).
export const WATERLOGGED_BY_DEFAULT_BLOCKS = ["sea_pickle"];
