import { BlockType } from "../../../blocks";

// Air-like blocks: the cell is empty.
export const EMPTY_SPACE_BLOCKS = ["air", "cave_air", "void_air", "light", "structure_void", "barrier"];

// Thin, tiny or purely functional structure blocks that have no game equivalent and are deliberately
// dropped to air (doors, signs, rails, redstone parts, ...). Family-wide drops live in material-families.ts.
export const INTENTIONALLY_DROPPED_EXACT_BLOCKS = new Set<string>([
  "fire",
  "soul_fire",
  "chain",
  "iron_bars",
  "ladder",
  "rail",
  "powered_rail",
  "detector_rail",
  "activator_rail",
  "lever",
  "tripwire",
  "tripwire_hook",
  "redstone_wire",
  "repeater",
  "comparator",
  "daylight_detector",
  "bell",
  "anvil",
  "chipped_anvil",
  "damaged_anvil",
  "cauldron",
  "water_cauldron",
  "lava_cauldron",
  "powder_snow_cauldron",
  "brewing_stand",
  "flower_pot",
  "scaffolding",
  "jigsaw",
  "structure_block",
  "end_portal",
  "grindstone",
  "piston_head",
  "skeleton_skull",
  "skeleton_wall_skull",
  "zombie_head",
  "creeper_head",
  "player_head",
  "wither_skeleton_skull",
  "glow_lichen",
  "sculk_vein",
  "spore_blossom",
  "amethyst_cluster",
  "large_amethyst_bud",
  "medium_amethyst_bud",
  "small_amethyst_bud",
  "candle",
  "candle_cake",
  "cake",
  "end_rod",
  "cocoa",
]);

// Solid furniture and machines, kept as a full block of a similar material so rooms stay enclosed.
export const STRUCTURE_SOLID_BLOCKS: Record<string, BlockType> = {
  chest: BlockType.PLANKS,
  trapped_chest: BlockType.PLANKS,
  barrel: BlockType.PLANKS,
  crafting_table: BlockType.PLANKS,
  cartography_table: BlockType.PLANKS,
  fletching_table: BlockType.PLANKS,
  smithing_table: BlockType.PLANKS,
  loom: BlockType.PLANKS,
  lectern: BlockType.PLANKS,
  bookshelf: BlockType.PLANKS,
  note_block: BlockType.PLANKS,
  jukebox: BlockType.PLANKS,
  composter: BlockType.PLANKS,
  beehive: BlockType.PLANKS,
  bee_nest: BlockType.PLANKS,
  furnace: BlockType.COBBLESTONE,
  blast_furnace: BlockType.COBBLESTONE,
  smoker: BlockType.COBBLESTONE,
  dispenser: BlockType.COBBLESTONE,
  dropper: BlockType.COBBLESTONE,
  observer: BlockType.COBBLESTONE,
  piston: BlockType.COBBLESTONE,
  sticky_piston: BlockType.COBBLESTONE,
  hopper: BlockType.COBBLESTONE,
  spawner: BlockType.COBBLESTONE,
  stonecutter: BlockType.STONE,
  decorated_pot: BlockType.TERRACOTTA,
  tnt: BlockType.TERRACOTTA_RED,
  target: BlockType.HAY_BLOCK,
  honey_block: BlockType.TERRACOTTA_ORANGE,
  honeycomb_block: BlockType.TERRACOTTA_ORANGE,
  glass: BlockType.GLASS,
  glass_pane: BlockType.GLASS,
  tinted_glass: BlockType.GLASS,
};
