// One priority queue per worker, for work that runs faster on the worker that did its neighbors (worldgen caches
// the terrain around each column). Keys belong to groups (affinity tiles); a group belongs to one worker and its keys
// land in that worker's queue. A worker takes its own best key, unless another queue holds work more than
// maxPriorityGapForAffinity more urgent or its own queue is empty. It then takes over the other queue's best group as
// a whole (all its keys move), so a tile is never generated by two workers that both rebuild its shared terrain;
// only a group its owner is working through right now is split, one key at a time.

import { profiler } from "../profiler";
import { PriorityScheduler } from "./priority-scheduler";

/** Metric names of one affinity queue set, built once. Per worker names are indexed by worker. */
class AffinityMetricNames {
  readonly enqueued: string;
  readonly removed: string;
  readonly reprioritizeAllCalls: string;
  readonly takeAttempts: string;
  readonly takenFromOwnQueue: string;
  readonly keptOwnWorkForAffinity: string;
  readonly stolenSingleKey: string;
  readonly stolenWholeGroup: string;
  readonly stolenGroupKeysMoved: string;
  readonly stealFoundNothing: string;
  readonly starved: string;
  readonly stealPriorityGapGauge: string;
  readonly stealScope: string;
  readonly takeScope: string;
  readonly totalDepthGauge: string;
  readonly groupCountGauge: string;
  readonly takenByWorker: string[] = [];
  readonly stolenByWorker: string[] = [];
  readonly stolenFromWorker: string[] = [];
  readonly depthGaugeByWorker: string[] = [];
  readonly workerLanes: string[] = [];

  constructor(lane: string, workerCount: number) {
    this.enqueued = `game.affinity.${lane}.enqueued`;
    this.removed = `game.affinity.${lane}.removed`;
    this.reprioritizeAllCalls = `game.affinity.${lane}.reprioritizeAllCalls`;
    this.takeAttempts = `game.affinity.${lane}.takeAttempts`;
    this.takenFromOwnQueue = `game.affinity.${lane}.takenFromOwnQueue`;
    this.keptOwnWorkForAffinity = `game.affinity.${lane}.keptOwnWorkForAffinity`;
    this.stolenSingleKey = `game.affinity.${lane}.stolenSingleKey`;
    this.stolenWholeGroup = `game.affinity.${lane}.stolenWholeGroup`;
    this.stolenGroupKeysMoved = `game.affinity.${lane}.stolenGroupKeysMoved`;
    this.stealFoundNothing = `game.affinity.${lane}.stealFoundNothing`;
    this.starved = `game.affinity.${lane}.starved`;
    this.stealPriorityGapGauge = `game.affinity.${lane}.stealPriorityGap`;
    this.stealScope = `main.affinity.${lane}.steal`;
    this.takeScope = `main.affinity.${lane}.takeFor`;
    this.totalDepthGauge = `queue.affinity.${lane}.total`;
    this.groupCountGauge = `queue.affinity.${lane}.groups`;
    for (let workerIndex = 0; workerIndex < workerCount; workerIndex++) {
      this.takenByWorker.push(`game.affinity.${lane}.worker${workerIndex}.taken`);
      this.stolenByWorker.push(`game.affinity.${lane}.worker${workerIndex}.stolenByIt`);
      this.stolenFromWorker.push(`game.affinity.${lane}.worker${workerIndex}.stolenFromIt`);
      this.depthGaugeByWorker.push(`queue.affinity.${lane}.worker${workerIndex}`);
      this.workerLanes.push(`${lane}.worker${workerIndex}`);
    }
  }
}

export class AffinityQueues {
  private readonly queues: PriorityScheduler<number>[];
  private readonly ownerByGroup = new Map<number, number>();
  private readonly keysByGroup = new Map<number, Set<number>>();
  private readonly priorityByKey = new Map<number, number>();
  private readonly currentGroupByWorker: (number | undefined)[];
  private readonly metrics: AffinityMetricNames;
  /** Off while the area around the player loads: then idle workers take single keys, so the nearest finish first. */
  transfersWholeGroups = true;

  constructor(
    readonly workerCount: number,
    private readonly preferredWorkerOf: (key: number) => number,
    public maxPriorityGapForAffinity = Number.POSITIVE_INFINITY,
    private readonly groupOf: (key: number) => number = (key) => key,
    profilerLane = "affinity",
  ) {
    this.metrics = new AffinityMetricNames(profilerLane, workerCount);
    this.queues = Array.from(
      { length: workerCount },
      (_, workerIndex) =>
        new PriorityScheduler<number>({
          profilerLane: this.metrics.workerLanes[workerIndex],
          profilerRollupLane: profilerLane,
        }),
    );
    this.currentGroupByWorker = new Array(workerCount).fill(undefined);
  }

  get size(): number {
    let total = 0;
    for (const queue of this.queues) total += queue.size;
    return total;
  }

  queuedFor(workerIndex: number): number {
    return this.queues[workerIndex]!.size;
  }

  has(key: number): boolean {
    return this.queues[this.ownerOfKey(key)]!.has(key);
  }

  schedule(key: number, priority: number): void {
    const group = this.groupOf(key);
    let keys = this.keysByGroup.get(group);
    if (!keys) this.keysByGroup.set(group, (keys = new Set()));
    keys.add(key);
    this.priorityByKey.set(key, priority);
    this.queues[this.ownerOfGroup(group, key)]!.schedule(key, key, priority);
    profiler.addCounter(this.metrics.enqueued);
  }

  remove(key: number): boolean {
    const removed = this.queues[this.ownerOfKey(key)]!.remove(key);
    this.forgetKey(key);
    if (removed) profiler.addCounter(this.metrics.removed);
    return removed;
  }

  reprioritizeAll(computePriority: (key: number) => number): void {
    profiler.addCounter(this.metrics.reprioritizeAllCalls);
    for (const queue of this.queues) {
      queue.reprioritizeAll((key) => {
        const priority = computePriority(key);
        this.priorityByKey.set(key, priority);
        return priority;
      });
    }
  }

  takeFor(workerIndex: number): number | undefined {
    const takeToken = profiler.begin(this.metrics.takeScope);
    try {
      return this.takeBestFor(workerIndex);
    } finally {
      profiler.end(takeToken);
    }
  }

  clear(): void {
    for (const queue of this.queues) queue.clear();
    this.ownerByGroup.clear();
    this.keysByGroup.clear();
    this.priorityByKey.clear();
    this.currentGroupByWorker.fill(undefined);
  }

  /** Publishes the depth of every worker's queue and the group count; call about once a second. */
  publishProfilerGauges(): void {
    if (!profiler.enabled) return;
    profiler.sampleGauge(this.metrics.totalDepthGauge, this.size);
    profiler.sampleGauge(this.metrics.groupCountGauge, this.keysByGroup.size);
    for (let workerIndex = 0; workerIndex < this.queues.length; workerIndex++) {
      profiler.sampleGauge(this.metrics.depthGaugeByWorker[workerIndex]!, this.queues[workerIndex]!.size);
      this.queues[workerIndex]!.publishProfilerGauges();
    }
  }

  private takeBestFor(workerIndex: number): number | undefined {
    profiler.addCounter(this.metrics.takeAttempts);
    const ownQueue = this.queues[workerIndex]!;
    let bestQueueIndex = -1;
    let bestPriority = Number.POSITIVE_INFINITY;
    for (let queueIndex = 0; queueIndex < this.queues.length; queueIndex++) {
      const priority = this.queues[queueIndex]!.peekPriority();
      if (priority !== undefined && priority < bestPriority) {
        bestPriority = priority;
        bestQueueIndex = queueIndex;
      }
    }
    const ownPriority = ownQueue.peekPriority();
    let key: number | undefined;
    if (bestQueueIndex === -1) {
      profiler.addCounter(this.metrics.starved);
      return undefined;
    }
    if (bestQueueIndex === workerIndex || (ownPriority !== undefined && ownPriority - bestPriority <= this.maxPriorityGapForAffinity)) {
      key = ownQueue.pop();
      if (key !== undefined) {
        profiler.addCounter(this.metrics.takenFromOwnQueue);
        if (bestQueueIndex !== workerIndex) profiler.addCounter(this.metrics.keptOwnWorkForAffinity);
      }
    } else {
      if (ownPriority !== undefined) profiler.sampleGauge(this.metrics.stealPriorityGapGauge, ownPriority - bestPriority);
      key = this.takeFromOtherWorker(workerIndex, bestQueueIndex);
    }
    if (key === undefined) return undefined;
    profiler.addCounter(this.metrics.takenByWorker[workerIndex]!);
    this.currentGroupByWorker[workerIndex] = this.groupOf(key);
    this.forgetKey(key);
    return key;
  }

  /** Moves the other worker's best group here, or takes one key when the other worker is in the middle of it. */
  private takeFromOtherWorker(workerIndex: number, otherWorkerIndex: number): number | undefined {
    const stealToken = profiler.begin(this.metrics.stealScope);
    try {
      return this.stealFromOtherWorker(workerIndex, otherWorkerIndex);
    } finally {
      profiler.end(stealToken);
    }
  }

  private stealFromOtherWorker(workerIndex: number, otherWorkerIndex: number): number | undefined {
    const otherQueue = this.queues[otherWorkerIndex]!;
    const bestKey = otherQueue.peek();
    if (bestKey === undefined) {
      profiler.addCounter(this.metrics.stealFoundNothing);
      return undefined;
    }
    const group = this.groupOf(bestKey);
    profiler.addCounter(this.metrics.stolenByWorker[workerIndex]!);
    profiler.addCounter(this.metrics.stolenFromWorker[otherWorkerIndex]!);
    if (!this.transfersWholeGroups || this.currentGroupByWorker[otherWorkerIndex] === group) {
      profiler.addCounter(this.metrics.stolenSingleKey);
      return otherQueue.pop();
    }
    const ownQueue = this.queues[workerIndex]!;
    this.ownerByGroup.set(group, workerIndex);
    let keysMoved = 0;
    for (const key of this.keysByGroup.get(group) ?? []) {
      if (otherQueue.moveTo(key, ownQueue, this.priorityByKey.get(key) ?? 0)) keysMoved++;
    }
    profiler.addCounter(this.metrics.stolenWholeGroup);
    profiler.addCounter(this.metrics.stolenGroupKeysMoved, keysMoved);
    return ownQueue.pop();
  }

  private forgetKey(key: number): void {
    this.priorityByKey.delete(key);
    const group = this.groupOf(key);
    const keys = this.keysByGroup.get(group);
    if (!keys) return;
    keys.delete(key);
    if (keys.size === 0) {
      this.keysByGroup.delete(group);
      this.ownerByGroup.delete(group);
    }
  }

  private ownerOfGroup(group: number, key: number): number {
    let owner = this.ownerByGroup.get(group);
    if (owner === undefined) {
      const preferred = this.preferredWorkerOf(key);
      owner = ((preferred % this.workerCount) + this.workerCount) % this.workerCount;
      this.ownerByGroup.set(group, owner);
    }
    return owner;
  }

  private ownerOfKey(key: number): number {
    const owner = this.ownerByGroup.get(this.groupOf(key));
    if (owner !== undefined) return owner;
    const preferred = this.preferredWorkerOf(key);
    return ((preferred % this.workerCount) + this.workerCount) % this.workerCount;
  }
}
