// One priority queue per worker, for work that runs faster on the worker that did its neighbors (worldgen caches
// the terrain around each column). Keys belong to groups (affinity tiles); a group belongs to one worker and its keys
// land in that worker's queue. A worker takes its own best key, unless another queue holds work more than
// maxPriorityGapForAffinity more urgent or its own queue is empty. It then takes over the other queue's best group as
// a whole (all its keys move), so a tile is never generated by two workers that both rebuild its shared terrain;
// only a group its owner is working through right now is split, one key at a time.

import { PriorityScheduler } from "./priority-scheduler";

export class AffinityQueues {
  private readonly queues: PriorityScheduler<number>[];
  private readonly ownerByGroup = new Map<number, number>();
  private readonly keysByGroup = new Map<number, Set<number>>();
  private readonly priorityByKey = new Map<number, number>();
  private readonly currentGroupByWorker: (number | undefined)[];
  /** Off while the area around the player loads: then idle workers take single keys, so the nearest finish first. */
  transfersWholeGroups = true;

  constructor(
    readonly workerCount: number,
    private readonly preferredWorkerOf: (key: number) => number,
    public maxPriorityGapForAffinity = Number.POSITIVE_INFINITY,
    private readonly groupOf: (key: number) => number = (key) => key,
  ) {
    this.queues = Array.from({ length: workerCount }, () => new PriorityScheduler<number>());
    this.currentGroupByWorker = new Array(workerCount).fill(undefined);
  }

  get size(): number {
    let total = 0;
    for (const queue of this.queues) total += queue.size;
    return total;
  }

  queuedFor(workerIndex: number): number {
    return this.queues[workerIndex]!.size;
  }

  has(key: number): boolean {
    return this.queues[this.ownerOfKey(key)]!.has(key);
  }

  schedule(key: number, priority: number): void {
    const group = this.groupOf(key);
    let keys = this.keysByGroup.get(group);
    if (!keys) this.keysByGroup.set(group, (keys = new Set()));
    keys.add(key);
    this.priorityByKey.set(key, priority);
    this.queues[this.ownerOfGroup(group, key)]!.schedule(key, key, priority);
  }

  remove(key: number): boolean {
    const removed = this.queues[this.ownerOfKey(key)]!.remove(key);
    this.forgetKey(key);
    return removed;
  }

  reprioritizeAll(computePriority: (key: number) => number): void {
    for (const queue of this.queues) {
      queue.reprioritizeAll((key) => {
        const priority = computePriority(key);
        this.priorityByKey.set(key, priority);
        return priority;
      });
    }
  }

  takeFor(workerIndex: number): number | undefined {
    const ownQueue = this.queues[workerIndex]!;
    let bestQueueIndex = -1;
    let bestPriority = Number.POSITIVE_INFINITY;
    for (let queueIndex = 0; queueIndex < this.queues.length; queueIndex++) {
      const priority = this.queues[queueIndex]!.peekPriority();
      if (priority !== undefined && priority < bestPriority) {
        bestPriority = priority;
        bestQueueIndex = queueIndex;
      }
    }
    const ownPriority = ownQueue.peekPriority();
    let key: number | undefined;
    if (bestQueueIndex === -1) return undefined;
    if (bestQueueIndex === workerIndex || (ownPriority !== undefined && ownPriority - bestPriority <= this.maxPriorityGapForAffinity)) {
      key = ownQueue.pop();
    } else {
      key = this.takeFromOtherWorker(workerIndex, bestQueueIndex);
    }
    if (key === undefined) return undefined;
    this.currentGroupByWorker[workerIndex] = this.groupOf(key);
    this.forgetKey(key);
    return key;
  }

  clear(): void {
    for (const queue of this.queues) queue.clear();
    this.ownerByGroup.clear();
    this.keysByGroup.clear();
    this.priorityByKey.clear();
    this.currentGroupByWorker.fill(undefined);
  }

  /** Moves the other worker's best group here, or takes one key when the other worker is in the middle of it. */
  private takeFromOtherWorker(workerIndex: number, otherWorkerIndex: number): number | undefined {
    const otherQueue = this.queues[otherWorkerIndex]!;
    const bestKey = otherQueue.peek();
    if (bestKey === undefined) return undefined;
    const group = this.groupOf(bestKey);
    if (!this.transfersWholeGroups || this.currentGroupByWorker[otherWorkerIndex] === group) return otherQueue.pop();
    const ownQueue = this.queues[workerIndex]!;
    this.ownerByGroup.set(group, workerIndex);
    for (const key of this.keysByGroup.get(group) ?? []) {
      if (!otherQueue.remove(key)) continue;
      ownQueue.schedule(key, key, this.priorityByKey.get(key) ?? 0);
    }
    return ownQueue.pop();
  }

  private forgetKey(key: number): void {
    this.priorityByKey.delete(key);
    const group = this.groupOf(key);
    const keys = this.keysByGroup.get(group);
    if (!keys) return;
    keys.delete(key);
    if (keys.size === 0) {
      this.keysByGroup.delete(group);
      this.ownerByGroup.delete(group);
    }
  }

  private ownerOfGroup(group: number, key: number): number {
    let owner = this.ownerByGroup.get(group);
    if (owner === undefined) {
      const preferred = this.preferredWorkerOf(key);
      owner = ((preferred % this.workerCount) + this.workerCount) % this.workerCount;
      this.ownerByGroup.set(group, owner);
    }
    return owner;
  }

  private ownerOfKey(key: number): number {
    const owner = this.ownerByGroup.get(this.groupOf(key));
    if (owner !== undefined) return owner;
    const preferred = this.preferredWorkerOf(key);
    return ((preferred % this.workerCount) + this.workerCount) % this.workerCount;
  }
}
