// Node-only generator: turns fixtures/block-behavior-reference.json.gz (recorded from the real 1.20.6 classes by
// fixtures/TreesReference.java) into block-behavior.generated.ts.
// Run: bun src/applications/game/worldgen/engine/features/feature-types/trees/generate-block-behavior-table.node.ts

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";

interface RecordedBlockValue {
  default: boolean | number;
  variants?: Record<string, boolean | number>;
}

interface RecordedBlockBehavior {
  solidRender: Record<string, RecordedBlockValue>;
  updateShapeAir: Record<string, RecordedBlockValue>;
}

const MODULE_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const recorded = JSON.parse(gunzipSync(readFileSync(join(MODULE_DIRECTORY, "fixtures", "block-behavior-reference.json.gz"))).toString()) as RecordedBlockBehavior;

function encode(value: boolean | number): string {
  return typeof value === "boolean" ? (value ? "1" : "0") : String(value);
}

function renderTable(name: string, valueType: string, table: Record<string, RecordedBlockValue>): string[] {
  const lines = [`export const ${name}: Record<string, readonly [defaultValue: ${valueType}, variants?: Record<string, ${valueType}>]> = {`];
  for (const [blockName, entry] of Object.entries(table).sort(([first], [second]) => first.localeCompare(second))) {
    const variants = entry.variants
      ? `, { ${Object.entries(entry.variants).map(([key, value]) => `${JSON.stringify(key)}: ${encode(value)}`).join(", ")} }`
      : "";
    lines.push(`  ${JSON.stringify(blockName)}: [${encode(entry.default)}${variants}],`);
  }
  lines.push("};", "");
  return lines;
}

const lines = [
  "// Generated by generate-block-behavior-table.node.ts from fixtures/block-behavior-reference.json.gz. Do not edit.",
  "// Per block: the default state's value and the values of the states that differ (keyed by the properties that",
  "// differ from the default state, sorted, as `key=value,key=value`).",
  "",
  "/** BlockState.isSolidRender; blocks with no solid-render state are absent. */",
  ...renderTable("SOLID_RENDER_TABLE", "0 | 1", recorded.solidRender),
  "/** Bit d (net.minecraft.core.Direction ordinal) is set when updateShape from direction d turns an unsupported block into air; absent blocks never do. */",
  ...renderTable("UPDATE_SHAPE_AIR_TABLE", "number", recorded.updateShapeAir),
];
writeFileSync(join(MODULE_DIRECTORY, "block-behavior.generated.ts"), lines.join("\n"));
console.log(`wrote ${Object.keys(recorded.solidRender).length} solid-render and ${Object.keys(recorded.updateShapeAir).length} update-shape blocks`);
