// A WorldGenRegion for decorating one origin chunk on demand. Reads see the base columns (terrain + surface,
// lazily generated by the BaseColumnSource) plus this decoration's own writes; writes are clipped to the 3x3
// chunks around the origin (writeRadiusCutoff = 1, as ChunkStatusTasks.generateFeatures sets up) and recorded so
// they can be replayed as a patch. Heightmaps follow ProtoChunk during the FEATURES step: the *_WG heightmaps
// stay as the base terrain left them, the four POST_FEATURES heightmaps are updated on every write.

import { type BlockStateCatalog, type BlockStateInfo, type BlockTagIndex, PaletteBlockInfo, SurvivalRules } from "../../block-state";
import type { BlockPalette, ChunkBlocks } from "../../chunk";
import { CarvingMask, type CarvingStep } from "../core/carving-mask";
import { ChunkHeightmap, HEIGHTMAP_TYPES, type HeightmapColumnReader, type HeightmapType, isWorldgenHeightmap } from "../core/heightmap";
import type { BaseColumnSource } from "./base-column-source";
import { VOID_AIR_STATE, type WorldGenLevel } from "./world-gen-level";

const WRITE_RADIUS = 1;
const LAYER_SIZE = 256;

class RegionColumn {
  blocks: Uint16Array;
  private copied = false;
  readonly writtenIndices = new Set<number>();
  private readonly heightmaps = new Map<HeightmapType, ChunkHeightmap>();

  constructor(
    readonly base: ChunkBlocks,
    private readonly paletteInfo: PaletteBlockInfo,
  ) {
    this.blocks = base.blocks;
  }

  write(index: number, paletteId: number): void {
    if (!this.copied) {
      this.blocks = new Uint16Array(this.base.blocks);
      this.copied = true;
    }
    this.blocks[index] = paletteId;
    this.writtenIndices.add(index);
  }

  heightmap(type: HeightmapType): ChunkHeightmap {
    let heightmap = this.heightmaps.get(type);
    if (!heightmap) {
      const useBaseBlocks = isWorldgenHeightmap(type);
      const minY = this.base.minY;
      const reader: HeightmapColumnReader = {
        minY,
        maxYExclusive: minY + this.base.height,
        infoAt: (localX, y, localZ) => {
          const index = (y - minY) * LAYER_SIZE + localZ * 16 + localX;
          return this.paletteInfo.info(useBaseBlocks ? this.base.blocks[index]! : this.blocks[index]!);
        },
      };
      heightmap = new ChunkHeightmap(type, reader);
      this.heightmaps.set(type, heightmap);
    }
    return heightmap;
  }

  /** ProtoChunk.setBlockState: POST_FEATURES heightmaps that exist are updated (missing ones prime lazily later). */
  updateHeightmaps(localX: number, y: number, localZ: number, info: BlockStateInfo): void {
    for (const type of HEIGHTMAP_TYPES) {
      if (isWorldgenHeightmap(type)) continue;
      this.heightmaps.get(type)?.update(localX, y, localZ, info);
    }
  }
}

/** Final values this decoration wrote into one chunk column (ascending block indices into ChunkBlocks.blocks). */
export interface ColumnPatch {
  readonly chunkX: number;
  readonly chunkZ: number;
  readonly indices: Int32Array;
  readonly paletteIds: Uint16Array;
}

export interface DecorationRegionParams {
  source: BaseColumnSource;
  seed: bigint;
  centerChunkX: number;
  centerChunkZ: number;
  blockStates: BlockStateCatalog;
  blockTags: BlockTagIndex;
  survival?: SurvivalRules;
}

export class DecorationRegion implements WorldGenLevel {
  readonly seed: bigint;
  readonly minY: number;
  readonly height: number;
  readonly seaLevel: number;
  readonly blockStates: BlockStateCatalog;
  readonly blockTags: BlockTagIndex;
  readonly survival: SurvivalRules;
  readonly centerChunkX: number;
  readonly centerChunkZ: number;
  private readonly source: BaseColumnSource;
  private readonly columns = new Map<number, RegionColumn>();
  private readonly carvingMasks = new Map<string, CarvingMask>();
  private palette: BlockPalette | undefined;
  private paletteInfo: PaletteBlockInfo | undefined;
  private readonly normalizedStateById: string[] = [];

  constructor(params: DecorationRegionParams) {
    this.source = params.source;
    this.seed = params.seed;
    this.centerChunkX = params.centerChunkX;
    this.centerChunkZ = params.centerChunkZ;
    this.minY = params.source.settings.minY;
    this.height = params.source.settings.height;
    this.seaLevel = params.source.settings.seaLevel;
    this.blockStates = params.blockStates;
    this.blockTags = params.blockTags;
    this.survival = params.survival ?? new SurvivalRules(params.blockStates);
  }

  private static columnKey(chunkX: number, chunkZ: number): number {
    // Chunk coordinates stay well inside +-2^20 for a 30M block world, so this packs losslessly.
    return (chunkX + 0x200000) * 0x400000 + (chunkZ + 0x200000);
  }

  private column(chunkX: number, chunkZ: number): RegionColumn {
    const key = DecorationRegion.columnKey(chunkX, chunkZ);
    let column = this.columns.get(key);
    if (!column) {
      const base = this.source.generateBaseColumn(chunkX, chunkZ);
      if (!this.palette) {
        this.palette = base.palette;
        this.paletteInfo = this.blockStates.forPalette(base.palette);
      } else if (base.palette !== this.palette) {
        throw new Error("BaseColumnSource columns must share one BlockPalette");
      }
      column = new RegionColumn(base, this.paletteInfo!);
      this.columns.set(key, column);
    }
    return column;
  }

  private normalizedState(paletteId: number): string {
    let state = this.normalizedStateById[paletteId];
    if (state === undefined) {
      state = this.blockStates.normalize(this.palette!.stateOf(paletteId));
      this.normalizedStateById[paletteId] = state;
    }
    return state;
  }

  private indexOf(x: number, y: number, z: number): number {
    return (y - this.minY) * LAYER_SIZE + (z & 15) * 16 + (x & 15);
  }

  isOutsideBuildHeight(y: number): boolean {
    return y < this.minY || y >= this.minY + this.height;
  }

  getBlockState(x: number, y: number, z: number): string {
    if (this.isOutsideBuildHeight(y)) return VOID_AIR_STATE;
    const column = this.column(x >> 4, z >> 4);
    return this.normalizedState(column.blocks[this.indexOf(x, y, z)]!);
  }

  getBlockInfo(x: number, y: number, z: number): BlockStateInfo {
    if (this.isOutsideBuildHeight(y)) return this.blockStates.info(VOID_AIR_STATE);
    const column = this.column(x >> 4, z >> 4);
    return this.paletteInfo!.info(column.blocks[this.indexOf(x, y, z)]!);
  }

  isEmptyBlock(x: number, y: number, z: number): boolean {
    return this.getBlockInfo(x, y, z).isAir;
  }

  ensureCanWrite(x: number, _y: number, z: number): boolean {
    return Math.abs((x >> 4) - this.centerChunkX) <= WRITE_RADIUS && Math.abs((z >> 4) - this.centerChunkZ) <= WRITE_RADIUS;
  }

  setBlock(x: number, y: number, z: number, state: string, _flags = 3): boolean {
    if (!this.ensureCanWrite(x, y, z)) return false;
    if (this.isOutsideBuildHeight(y)) return true;
    const column = this.column(x >> 4, z >> 4);
    const normalized = this.blockStates.normalize(state);
    const paletteId = this.palette!.idOf(normalized);
    column.write(this.indexOf(x, y, z), paletteId);
    column.updateHeightmaps(x & 15, y, z & 15, this.paletteInfo!.info(paletteId));
    return true;
  }

  getHeight(type: HeightmapType, x: number, z: number): number {
    return this.column(x >> 4, z >> 4).heightmap(type).getFirstAvailable(x & 15, z & 15);
  }

  getBiome(x: number, y: number, z: number): string {
    return this.source.biomeAt(x, y, z);
  }

  /** Protochunks are not lit until after FEATURES, so every position reads as dark (see engine/features/README.md). */
  getRawBrightness(_x: number, _y: number, _z: number): number {
    return 0;
  }

  getCarvingMask(chunkX: number, chunkZ: number, step: CarvingStep): CarvingMask {
    const key = `${chunkX},${chunkZ},${step}`;
    let mask = this.carvingMasks.get(key);
    if (!mask) {
      mask = this.source.carvingMask?.(chunkX, chunkZ, step) ?? new CarvingMask(this.minY, this.height);
      this.carvingMasks.set(key, mask);
    }
    return mask;
  }

  /** The palette shared by every column (available once any block has been read). */
  get blockPalette(): BlockPalette | undefined {
    return this.palette;
  }

  /** Everything written into the writable 3x3 chunks, as final values per position. */
  extractPatches(): ColumnPatch[] {
    const patches: ColumnPatch[] = [];
    for (let chunkZ = this.centerChunkZ - WRITE_RADIUS; chunkZ <= this.centerChunkZ + WRITE_RADIUS; chunkZ++) {
      for (let chunkX = this.centerChunkX - WRITE_RADIUS; chunkX <= this.centerChunkX + WRITE_RADIUS; chunkX++) {
        const column = this.columns.get(DecorationRegion.columnKey(chunkX, chunkZ));
        if (!column || column.writtenIndices.size === 0) continue;
        const indices = Int32Array.from(column.writtenIndices).sort();
        const paletteIds = new Uint16Array(indices.length);
        for (let position = 0; position < indices.length; position++) paletteIds[position] = column.blocks[indices[position]!]!;
        patches.push({ chunkX, chunkZ, indices, paletteIds });
      }
    }
    return patches;
  }
}
